### ISSUE TITLE
change packaging to not require default health check scripts

### ISSUE THREAD

**Issue by miabbott** [fedora-iot/greenboot#117]
The currently available default health check scripts which are [required](https://github.com/fedora-iot/greenboot/tree/main/usr/lib/greenboot/check/required.d) do not have the level of reliability we desire for Edge device scenarios.

See #68, #71, #90, #93, #98 for examples of difficulties, failures, etc of the scripts

Until we are able to provide more resilient health checks by default, we should package the existing scripts in a separate RPM and have it be an optional install.

**Comment by say-paul** [comment]
The  health-check is distributed as separate [package](https://github.com/fedora-iot/greenboot/blob/5df8872c9cb7d19edec3e6c2bcbf1a660290a293/greenboot.spec#L41). 
But its installed by default via image-builder for r4e.

**Comment by miabbott** [comment]
> But installed by default via image-builder for [r4e](https://github.com/osbuild/images/blob/53883800856574edb8c03663a3c2411c76e99059/pkg/distro/rhel9/edge.go#L550)

Thanks for pointing that out; I'd say we should stop including the subpackage by default in Fedora IoT/R4E until we have more confidence in health checks.

**Comment by say-paul** [comment]
PR: https://github.com/osbuild/images/pull/179

**Comment by say-paul** [comment]
Yes, We would be looking for options to make it configurable, I would still keep the PR until we decide how to package the default-health-check if we want to make it configurable from greenboot.

**Comment by 7flying** [comment]
Ideas:
- We agree that we should not remove the default checks RPM.
- We should configure the checks two ways: is it enabled/disabled (use a list for this), and is it required or wanted (in case that it is enabled).
- We are going to use a single config file instead of using directories to express configuration.

Other things to consider:
- How are we going to handle "old" greenboot versions that still have the `required.d` and `wanted.d` ?
- How are we going to handle config upgrades with new health checks?

Future:
- Allow overriding "default" config file if another file is found at X directory.
